name: 'Netflex Site information'
description: 'Gets information about the site'
inputs:
  token:  
    description: 'OIDC Token for the site'
    default: ""
  audience:
    description: 'OIDC Token audience. Will only be used if token is not set'
    default: 'orc.apility.dev'
outputs:
  publicKey:
    description: "Site public key"
    value: ${{ steps.info.outputs.publicKey }}
  privateKey:
    description: "Site private key"
    value: ${{ steps.info.outputs.privateKey }}
  alias:
    description: "Site alias"
    value: ${{ steps.info.outputs.siteAlias }}
runs:
  using: "composite"
  steps:
    - name: Create token
      if: inputs.token == ''
      shell: bash
      id: oidc
      run: |
        TOKEN=$(curl -sLS "${ACTIONS_ID_TOKEN_REQUEST_URL}&audience=$AUDIENCE" -H "User-Agent: actions/oidc-client" -H "Authorization: Bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN")
        echo "::set-output name=token::$(echo $TOKEN | jq -r .value)"
      env:
        AUDIENCE: ${{ inputs.audience }}
    - name: Get site info
      id: info
      shell: bash
      run: |
        curl -H "Authorization:Bearer $OIDC_TOKEN" -H "Accepts:application/github-output" https://orc.apility.dev/info
      env:
        OIDC_TOKEN: ${{ steps.oidc.outputs.token }}${{ inputs.token }}